# 获取专辑内容
GET http://{{host}}/album?id=32311
Accept: application/json

###
# 专辑动态信息
GET http://{{host}}/album/detail/dynamic?id=32311
Accept: application/json

###
# 收藏/取消收藏专辑
GET http://{{host}}/album/sub?id=32311&t=0
Accept: application/json

###
# 获取已收藏专辑列表
GET http://{{host}}/album/sublist
Accept: application/json

###
# 最新专辑
GET http://{{host}}/album/newest
Accept: application/json

###
# 全部新碟
GET http://{{host}}/album/new?area=KR&limit=10
Accept: application/json

###
# 数字专辑-新碟上架
GET http://{{host}}/album/list?limit=10
Accept: application/json

###
# 数字专辑&数字单曲-榜单
GET http://{{host}}/album/songsaleboard?type=year&year=2020&albumType=0
Accept: application/json

###
# 数字专辑-语种风格馆
GET http://{{host}}/album/list/style?area=Z_H&offset=2
Accept: application/json

###
# 数字专辑详情
GET http://{{host}}/album/detail?id=84547195
Accept: application/json

###
