# 歌手分类
GET http://{{host}}/artist/list?type=1&area=96&initial=b
Accept: application/json

###
# 收藏/取消收藏歌手
GET http://{{host}}/artist/sub?id=6452&t=1
Accept: application/json

###
# 歌手热门50首歌曲
GET http://{{host}}/artist/top/song?id=125527
Accept: application/json

###
# 收藏的歌手列表
GET http://{{host}}/artist/sublist
Accept: application/json

###
# 获取歌手单曲
GET http://{{host}}/artists?id=6452
Accept: application/json

###
# 获取歌手 mv
GET http://{{host}}/artist/mv?id=6452
Accept: application/json

###
# 获取歌手专辑
GET http://{{host}}/artist/album?id=6452&limit=30
Accept: application/json

###
# 获取歌手描述
GET http://{{host}}/artist/desc?id=6452
Accept: application/json

###
# 歌手全部歌曲
GET http://{{host}}/artist/songs?id=6452
Accept: application/json

###
