# 获取动态评论
GET http://{{host}}/comment/event?threadId=A_EV_2_6559519868_32953014
Accept: application/json

###
# 云村热评
GET http://{{host}}/comment/hotwall/list
Accept: application/json

###
# 歌曲评论
GET http://{{host}}/comment/music?id=186016&limit=1
Accept: application/json

###
# 专辑评论
GET http://{{host}}/comment/album?id=32311
Accept: application/json

###
# 歌单评论
GET http://{{host}}/comment/playlist?id=705123491
Accept: application/json

###
# mv 评论
GET http://{{host}}/comment/mv?id=5436712
Accept: application/json

###
# 电台节目评论
GET http://{{host}}/comment/dj?id=794062371
Accept: application/json

###
# 视频评论
GET http://{{host}}/comment/video?id=89ADDE33C0AAE8EC14B99F6750DB954D
Accept: application/json

###
# 热门评论
GET http://{{host}}/comment/hot?id=186016&type=0
Accept: application/json

###
# 给评论点赞
GET http://{{host}}/comment/like?id=29178366&cid=12840183&t=1&type=0
Accept: application/json

###
# 发送评论
GET http://{{host}}/comment?t=1&type=1&id=5436712&content=test
Accept: application/json

###
# 删除评论
GET http://{{host}}/comment?t=0&type=1&id=5436712&commentId=3193845528
Accept: application/json

###
