# 获取动态评论
GET http://{{host}}/comment/event?threadId=A_EV_2_6559519868_32953014
Accept: application/json

###
# 云村热评
GET http://{{host}}/comment/hotwall/list
Accept: application/json

###
# 歌曲评论
GET http://{{host}}/comment/music?id=186016&limit=1
Accept: application/json

###
