# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
GET http://{{host}}/
# 测试
Accept: application/json

###
# 手机号登录
GET http://{{host}}/login/cellphone?phone={{phone}}&password={{password}}
Accept: application/json

###
# 邮箱登录
GET http://{{host}}/login?email={{email}}&password={{email_password}}
Accept: application/json

###
# 刷新登录
GET http://{{host}}/login/refresh
Accept: application/json

###
# 登录状态
GET http://{{host}}/login/status
Accept: application/json

###
# 退出登录
GET http://{{host}}/logout
Accept: application/json

###
