# 收藏/取消收藏 MV
GET http://{{host}}/mv/sub?mvid=123&t=1
Accept: application/json

###
# 收藏的 MV 列表
GET http://{{host}}/mv/sublist
Accept: application/json

###
# 热门歌单分类
GET http://{{host}}/playlist/hot
Accept: application/json

###
# 全部 mv
GET http://{{host}}/mv/all?area=港台
Accept: application/json

###
# 最新 mv
GET http://{{host}}/mv/first?limit=10
Accept: application/json

###
# 网易出品mv
GET http://{{host}}/mv/exclusive/rcmd?limit=10
Accept: application/json

###
# 获取 mv 数据
GET http://{{host}}/mv/detail?mvid=5436712
Accept: application/json

###
# mv 地址
GET http://{{host}}/mv/url?id=5436712
Accept: application/json

###
# 获取 mv 点赞转发评论数数据
GET http://{{host}}/mv/detail/info?mvid=5436712
Accept: application/json

###
