# 获取热门话题
GET http://{{host}}/hot/topic
Accept: application/json

###
# 智能播放
GET http://{{host}}/playmode/intelligence/list?id=33894312&pid=24381616
Accept: application/json

###
# 获取歌词
GET http://{{host}}/lyric?id=385965
Accept: application/json

###
# banner
GET http://{{host}}/banner?type=2
Accept: application/json

###
# 资源点赞( MV,电台,视频)
GET http://{{host}}/resource/like?t=1&type=1&id=5436712
Accept: application/json

###
# 听歌打卡
GET http://{{host}}/scrobble?id=518066366&sourceid=36780169&time=291
Accept: application/json

###
# batch批量请求接口
GET http://{{host}}/batch?/api/v2/banner/get={"clientType":"pc"}
Accept: application/json

###
# 国家编码列表
GET http://{{host}}/countries/code/list
Accept: application/json

###
# 音乐日历
GET http://{{host}}/calendar?startTime=1606752000000&endTime=1609430399999
Accept: application/json

###
# 收藏的专栏
GET http://{{host}}/topic/sublist?limit=2&offset=1
Accept: application/json

###
# 获取话题详情
GET http://{{host}}/topic/detail?actid=111551188
Accept: application/json

###
# 获取话题详情热门动态
GET http://{{host}}/topic/detail/event/hot?actid=111551188
Accept: application/json

###
# 一起听状态
GET http://{{host}}/listen/together/status
Accept: application/json

###
