# 获取热门话题
GET http://{{host}}/hot/topic
Accept: application/json

###
# 智能播放
GET http://{{host}}/playmode/intelligence/list?id=33894312&pid=24381616
Accept: application/json

###
# 获取歌词
GET http://{{host}}/lyric?id=385965
Accept: application/json

###
# banner
GET http://{{host}}/banner?type=2
Accept: application/json

###
# 资源点赞( MV,电台,视频)
GET http://{{host}}/resource/like?t=1&type=1&id=5436712
Accept: application/json

###
