# 更新歌单
GET http://{{host}}/playlist/update?id=24381616&name=新歌单&desc=描述&tags=学习
Accept: application/json

###
# 更新歌单描述
GET http://{{host}}/playlist/desc/update?id=24381616&desc=描述
Accept: application/json

###
# 更新歌单名
GET http://{{host}}/playlist/name/update?id=24381616&name=歌单名
Accept: application/json

###
# 更新歌单标签
GET http://{{host}}/tags/update?id=24381616&tags=学习
Accept: application/json

###
# 获取歌单详情
GET http://{{host}}/playlist/detail?id=1
Accept: application/json

###
# 新建歌单
GET http://{{host}}/playlist/create?name=测试歌单
Accept: application/json

###
# 删除歌单
GET http://{{host}}/playlist/delete?id=4859457068
Accept: application/json

###
# 收藏/取消收藏歌单
GET http://{{host}}/playlist/subscribe?id=106697785&t=2
Accept: application/json

###
# 歌单收藏者
GET http://{{host}}/playlist/subscribers?id=106697785&limit=30
Accept: application/json

###
# 对歌单添加或删除歌曲
GET http://{{host}}/playlist/tracks?op=add&pid=4859457068&tracks=385965
Accept: application/json

###
