# 发送私信
GET http://{{host}}/send/text?user_ids=32953014&msg=test
Accept: application/json

###
# 发送私信(带歌单)
GET http://{{host}}/send/playlist?msg=test&user_ids=475625142&playlist=705123491
Accept: application/json

###
# 发送私信音乐
GET http://{{host}}/send/song?user_ids=1&id=351318&msg=测试
Accept: application/json

###
# 发送私信(带专辑)
GET http://{{host}}/send/album?user_ids=1&id=351318&msg=测试
Accept: application/json

###
