# 获取音乐 url
GET http://{{host}}/song/url?id=405998841,33894312
Accept: application/json

###
# 音乐是否可用
GET http://{{host}}/check/music?id=385965
Accept: application/json

###
# 获取歌曲详情
GET http://{{host}}/song/detail?ids=347230,347231
Accept: application/json

###
# 调整歌曲顺序
GET http://{{host}}/song/order/update?pid=2039116066&ids=[5268328,1219871]
Accept: application/json

###
