# 歌单 ( 网友精选碟 )
GET http://{{host}}/top/playlist?limit=10&order=new
Accept: application/json

###
# 获取精品歌单
GET http://{{host}}/top/playlist/highquality?before=1503639064232&limit=3
Accept: application/json

###
# 新歌速递
GET http://{{host}}/top/song?type=0
Accept: application/json

###
# 新碟上架
GET http://{{host}}/top/album?offset=0&limit=30
Accept: application/json

###
# 热门歌手
GET http://{{host}}/top/artists?offset=0&limit=30
Accept: application/json

###
