###
# 获取用户详情
GET http://{{host}}/user/detail?uid={{uid}}
Accept: application/json

###
# 获取用户信息 , 歌单，收藏，mv, dj 数量
GET http://{{host}}/user/subcount
Accept: application/json

###
# 更新用户信息
GET http://{{host}}/user/update?gender=0&signature=测试签名&city=440300&nickname=binary&birthday=1525918298004&province=440000
Accept: application/json

###
# 获取用户歌单
GET http://{{host}}/user/playlist?uid={{uid}}
Accept: application/json

###
# 获取用户电台
GET http://{{host}}/user/dj?uid={{uid}}
Accept: application/json

###
# 获取用户关注列表
GET http://{{host}}/user/follows?uid={{uid}}
Accept: application/json

###
# 获取用户粉丝列表
GET http://{{host}}/user/followeds?uid={{uid}}
Accept: application/json

###
# 获取用户动态
GET http://{{host}}/user/event?uid={{uid}}
Accept: application/json

###
# 关注/取消关注用户
GET http://{{host}}/follow?id=32953014&t=1
Accept: application/json

###
# 获取用户播放记录
GET http://{{host}}/user/record?uid={{uid}}&type=1
Accept: application/json

###
# 私人 FM
GET http://{{host}}/personal_fm
Accept: application/json

###
# 签到
GET http://{{host}}/daily_signin
Accept: application/json

###
# 喜欢音乐
GET http://{{host}}/like?id=347230
Accept: application/json

###
# 喜欢音乐列表
GET http://{{host}}/likelist?uid=32953014
Accept: application/json

###
# 垃圾桶
GET http://{{host}}}/fm_trash?id=347230
Accept: application/json

###
# 云盘
GET http://{{host}}/user/cloud
Accept: application/json

###
# 云盘歌曲删除
GET http://{{host}}/user/cloud/del
Accept: application/json

###
# 云盘数据详情
GET http://{{host}}/user/cloud/detail?id=5374627
Accept: application/json

###
# 用户电台
GET http://{{host}}/user/audio?uid=32953014
Accept: application/json

###
# 设置
GET http://{{host}}/setting
Accept: application/json

###
# 获取用户等级信息
GET http://{{host}}/user/level
Accept: application/json

###
# TODO:更新头像
